site_name: 程序设计训练（Python）
site_description: 'Documentation for Crawler Programming Assignment of Programming and Training (Python) Course'
site_author: '程序设计训练 Python 教学组'
copyright: 'Copyright &copy; 2023-2025 清华大学程序设计训练 Python 教学组。All Rights Reserved.'

repo_name: 'python-course/python-docs'
repo_url: 'https://git.tsinghua.edu.cn/python-course/python-docs'

nav:
  - 课程概述: index.md
  - 实验一：爬虫与信息系统: 
    - 实验概述: crawler/index.md
    - 实验内容:
      - 爬虫: crawler/project/crawler.md
      - Web系统设计: crawler/project/web.md
      - 数据分析: crawler/project/analysis.md
    - 实验指导:
      - 爬虫: crawler/ref/crawler.md
      - Web系统设计: crawler/ref/django.md
      - 自然语言处理与信息检索: crawler/ref/analysis.md
      - 数据可视化: crawler/ref/visualize.md
    - 评分标准: crawler/requirements.md
    - FAQ: crawler/faq.md

  - 实验二：在线评测系统:
    - 实验概述: oj/index.md
    - 实验内容:
      - Step1：题目管理: oj/project/step1.md
      - Step2：题目评测: oj/project/step2.md
      - Step3：评测列表: oj/project/step3.md
      - Step4：用户管理: oj/project/step4.md
      - Step5：日志与权限: oj/project/step5.md
      - Step6：持久化存储: oj/project/step6.md
      - Adv1：特殊题目评测: oj/project/advance1.md
      - Adv2：前端交互: oj/project/advance2.md
      - Adv3：安全机制: oj/project/advance3.md
      - Adv4：代码查重: oj/project/advance4.md
    - API 文档: oj/api.md
    - 评分标准: oj/requirements.md
    - FAQ: oj/faq.md
    - 仓库拉取教程: oj/gitpull.md

    - "附录：本地 Git 安装与配置指南": crawler/git.md
  # - 实验二：MiniGPT:
  #   - 实验概述: MiniGPT/index.md
  #   - 实验内容:
  #     - 数据集和预处理介绍: MiniGPT/projects/dataset.md
  #     - 模型训练和微调: MiniGPT/projects/training.md
  #     - 模型推理与评估: MiniGPT/projects/evaluation.md
  #     - 聊天机器人竞技场: MiniGPT/projects/chatbot_arena.md
  #   - 实验知识补充:
  #     - 语言模型微调的知识补充: MiniGPT/ref/background.md
  #   - 评分标准: MiniGPT/requirements.md
  #   - FAQ: MiniGPT/faq.md


theme:
  name: material
  language: 'zh'
  custom_dir: 'theme-override/'
  features:
    - navigation.instant
    - navigation.expand
    - search.suggest
    - search.highlight
    - search.share

# Strategy: Use an absolute path
markdown_extensions:
  - attr_list
  - pymdownx.pathconverter:
      base_path: '' # default: ''
      relative_path: '' # default ''
      absolute: false # default: false
      tags: 'a script img link object embed'
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.arithmatex:
      generic: true
  - md_in_html
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://fastly.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - 'https://cdn.jsdelivr.net/npm/wavedrom@2.1.2/wavedrom.unpkg.js'

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      locale: zh
  - git-authors:
      encoding: latin1
      show_contribution: true
      show_line_count: true
  - glightbox

extra:
  analytics:
    provider: google
    property: G-69YPS2LP7R
